/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.0 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat Jan 23 16:31:08 2016
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


