/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.0 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat Oct 24 12:05:16 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


