#include "mediatek/custom/lightning72_wet_l_jb3/cgen/cfgdefault/CFG_Audio_Default_Cust.h"
#include "mediatek/custom/lightning72_wet_l_jb3/cgen/cfgdefault/CFG_Custom1_Default.h"
#include "mediatek/custom/lightning72_wet_l_jb3/cgen/cfgdefault/CFG_GPS_Default.h"
#include "mediatek/custom/lightning72_wet_l_jb3/cgen/cfgdefault/CFG_PRODUCT_INFO_Default.h"
#include "mediatek/custom/lightning72_wet_l_jb3/cgen/cfgdefault/CFG_WIFI_Default.h"
