BOOT_LOGO = hvga

CUSTOM_KERNEL_DCT=mdk

MTK_BUILD_VERNO=AP7200-MDK.V027

DEFAULT_INPUT_METHOD = com.tencent.qqpinyin.QQPYInputMethodService
QQ_INPUT_IME = yes

MTK_FM_SUPPORT = no
MTK_FM_RECORDING_SUPPORT = no

MTK_SIGNATURE_CUSTOMIZATION=yes
GEENK_SPEECH_SERVICE = yes
SU_FOR_SYSTEM_APP = yes
QQ_PHONEBOOK = yes
